# Generated by Django 4.2.6 on 2023-10-28 01:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing_comment_category_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="watchlistedBy",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.AddField(
            model_name="listing",
            name="watchlistedBy",
            field=models.ManyToManyField(
                blank=True, related_name="watchlist", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
