# Generated by Django 4.2.6 on 2023-10-30 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_category_listing_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="categories",
        ),
        migrations.AddField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="auctions.category",
            ),
        ),
    ]
