# Generated by Django 4.2.6 on 2023-10-30 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_remove_listing_categories_listing_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="auctions.category",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="watchlistedBy",
            field=models.ManyToManyField(
                null=True, related_name="watchlist", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
