# Generated by Django 4.2.6 on 2023-11-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_rename_name_category_catname"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="commentTitle",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
