# Generated by Django 4.2.6 on 2023-11-02 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_comment_commenttitle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="active",
        ),
    ]
