# Generated by Django 4.2.6 on 2023-11-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_remove_bid_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="winningBid",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
