# Generated by Django 4.2.6 on 2023-11-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_listing_winningbid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="imgLink",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
