# Generated by Django 4.2.6 on 2023-11-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_alter_listing_imglink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="category",
        ),
        migrations.AddField(
            model_name="listing",
            name="category",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="listings", to="auctions.category"
            ),
        ),
    ]
